### ISSUE TITLE
Issues with creation of injection.json file for Bu2019lm

### ISSUE THREAD

**Issue by ritwiksharma049** [nuclear-multimessenger-astronomy/nmma#31]
I ran this command line for creating injection.json for Bu2019lm:

nmma_create_injection --prior-file priors/Bu2019lm.prior --injection-file example_files/sim_events/injections.dat --eos-file example_files/eos/ALF2.dat --binary-type BNS --n-injection 100 --original-parameters --extension json --aligned-spin

and got this error: 

File "/home/exouser/anaconda3/lib/python3.9/site-packages/nmma-0.0.1-py3.9.egg/nmma/eos/create_injection.py", line 317, in main
    injection_creator = InjectionCreator(
TypeError: __init__() got an unexpected keyword argument 'gps_file'

**Comment by mcoughlin** [comment]
https://github.com/lscsoft/bilby_pipe/blob/master/bilby_pipe/create_injections.py#L145

It looks to be there in recent releases (I would guess). What is your version of bilby_pipe?

**Comment by ritwiksharma049** [comment]
bilby_pipe --version gives this:

bilby_pipe=1.0.6: (CLEAN) e9f88c2 2022-04-25 07:38:56 +0000 bilby=1.1.5: release

**Comment by ritwiksharma049** [comment]
Okay bilby_pipe 1.0.5 creates injection.json.

We should probably add this in the requirements, if it is worth it.

**Comment by mcoughlin** [comment]
Is this a problem in the old bilby_pipe or new bilby_pipe? Specifying the requirement is good, I just want to know if we need to working towards fixing if it is depracated behavior.

**Comment by ritwiksharma049** [comment]
It's an issue with the new bilby_pipe (1.0.6). It works fine with 1.0.5.
I'll make a PR for the requirements file if required.

**Comment by mcoughlin** [comment]
You should pin to the working version. I am asking if you have looked into the new code version to see what is required to fix ours.

**Comment by ritwiksharma049** [comment]
Actually I haven't had a look over our code and see what's missing. I went
ahead with 1.0.5.

**Comment by tsunhopang** [comment]
Could you try bilby_pipe==1.0.5 and see?

**Comment by ritwiksharma049** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
parallel-bilby 1.1.0 requires bilby-pipe>=1.0.6, but you have bilby-pipe 1.0.5 which is incompatible.

I got this as an error, but it installed 1.0.5 nevertheless.

**Comment by ritwiksharma049** [comment]
Successfully installed bilby-1.2.1 bilby-pipe-1.0.5 dynesty-1.0.1 lalsuite-7.10 pyfftw-0.13.0

These versions of packages besides bilby-pipe were installed after uninstallation of the existing ones. 

Found existing installation: dynesty 2.0.0
    Uninstalling dynesty-2.0.0:
      Successfully uninstalled dynesty-2.0.0
  Attempting uninstall: bilby
    Found existing installation: bilby 1.1.3
    Uninstalling bilby-1.1.3:
      Successfully uninstalled bilby-1.1.3      (Some existing versions before the switch from 1.0.4 to 1.0.5

**Comment by ritwiksharma049** [comment]
But the original issue is resolved.

nmma_create_injection --prior-file priors/Bu2019lm.prior --injection-file example_files/sim_events/injections.dat --eos-file example_files/eos/ALF2.dat --binary-type BNS --n-injection 100 --original-parameters --extension json --aligned-spin

works fine.

**Comment by ritwiksharma049** [comment]
@mcoughlin can we close this? The original command line worked with bilby-pipe 1.0.5. What do you think?
