### ISSUE TITLE
FiestaModel breaks with fiestaEM>=0.2.2: BullaFlux/BullaLightcurveModel removed

### ISSUE THREAD

**Issue by ThibeauWouters** [nuclear-multimessenger-astronomy/nmma#440]
## Summary

`nmma.em.model.FiestaModel.__init__` (and the GRB equivalent) imports
`BullaFlux` / `BullaLightcurveModel` from `fiesta.inference.lightcurve_model`:

```python
# nmma/em/model.py
def __init__(self, model="Bu2026_MLP", filters=None, surrogate_dir=None, **kwargs):
    if model.endswith("_lc"):
        from fiesta.inference.lightcurve_model import (
            BullaLightcurveModel as BullaSurrogate,
        )
    else:
        from fiesta.inference.lightcurve_model import BullaFlux as BullaSurrogate
    ...
```

These two class names were removed from `fiestaEM` on 2026-09-07
(nuclear-multimessenger-astronomy/fiestaEM@0fbeac5, "Improve filter handling
for the CombinedSurrogate class"), replaced by a more generic
`SurrogateModel` / `FluxModel` / `LightcurveModel` / `CombinedSurrogate` +
`built_in_surrogates` registry design. `fiestaEM` `v0.2.2` was tagged
2026-09-09 and already includes that removal.

`nmma`'s `pyproject.toml` pins `fiestaEM>=0.2.1`, which permits `0.2.2`. So a
fresh `pip install nmma` (or an existing install where `fiestaEM` gets
upgraded) currently gets a broken `FiestaModel`:

```
ImportError: cannot import name 'BullaFlux' from 'fiesta.inference.lightcurve_model'
```

This affects `main` directly (confirmed on both `main` and `sampler_plugin`
as of the commit `nmma` is at while I found this) — it's not specific to any
downstream config or branch.

## Reproduction

With `fiestaEM==0.2.2` installed (the current latest release):

```python
import nmma.em.model as model
model.FiestaModel(model="Bu2026_MLP")
# or any analysis with em-transient-class: fiesta_kn / fiesta_grb
```

```
Traceback (most recent call last):
  ...
  File ".../nmma/em/model.py", line 785, in __init__
    from fiesta.inference.lightcurve_model import BullaFlux as BullaSurrogate
ImportError: cannot import name 'BullaFlux' from 'fiesta.inference.lightcurve_model'
```

## Environment

- `nmma`: `main` / `sampler_plugin` (both affected identically on this file)
- `fiestaEM==0.2.2` (also confirmed still broken on current `fiestaEM` `main`,
  1 commit ahead of `v0.2.2`)
- Works correctly with `fiestaEM==0.2.1` (2026-07-08), the last release
  before the rename — this is also the oldest version that satisfies nmma's
  own `fiestaEM>=0.2.1` constraint, so it's not a coincidence that pinning to
  it is a viable workaround.
- Python 3.12

## Possible fixes (not implementing any of these — filing for the maintainers to weigh in)

1. **Tighten the dependency pin** in `pyproject.toml` to
   `fiestaEM>=0.2.1,<0.2.2` (or an explicit `==0.2.1`) as a stopgap, so `pip
   install nmma` doesn't silently pull in an incompatible `fiestaEM`. Cheapest
   fix, but freezes out any future `fiestaEM` improvements/fixes released
   under `0.2.x`.
2. **Update `FiestaModel`/`GRBFiestaModel` to use fiestaEM's new API**
   (`SurrogateModel` / `FluxModel` / `LightcurveModel` / `CombinedSurrogate`
   and the `built_in_surrogates` registry) instead of the removed
   `BullaFlux`/`BullaLightcurveModel` names. The real fix, but needs someone
   familiar with both the old and new `fiestaEM` model-construction API to
   map `model=` / `filters=` / `directory=` correctly onto the new
   constructors.
3. **Coordinate with `fiestaEM` upstream** to either keep short
   backwards-compatible aliases (`BullaFlux = FluxModel` /
   `BullaLightcurveModel = LightcurveModel`, if those really are 1:1
   replacements) for one more release, or add a changelog/deprecation note
   pointing consumers at the new API before further breaking renames land in
   a patch release like `0.2.2` did here.

Happy to help test a fix — found this while validating whether existing NMMA
analyses (specifically GW+KN+EOS configs using `em-transient-class: fiesta_kn`)
still run end-to-end against current released dependencies.

**Comment by ThibeauWouters** [comment]
Fixed into dev in #443
